name: Deploy React App to GCS

on:
  push:
    branches:
      - main # main 브랜치에 push될 때마다 워크플로우 실행

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # GCP 프로젝트 ID (GitHub Secrets 사용)
  GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }} # GCS 버킷 이름 (GitHub Secrets 사용)

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write' # OIDC 토큰을 발행하기 위해 필요

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: PROD_ENV 설정 로드
        run: echo "${{ secrets.PROD_ENV }}" > ./.env

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'github-actions-gcs-deployer@theta-anchor-465201-q4.iam.gserviceaccount.com'

      - name: Upload build files to GCS
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          # React 빌드 결과물이 있는 폴더 경로 (일반적으로 'build' 또는 'dist')
          path: './build'
          # 업로드할 GCS 버킷 이름
          destination: ${{ env.GCS_BUCKET_NAME }}
          # 버킷의 루트에 직접 업로드하려면 '.' 또는 ''
          # 특정 경로에 업로드하려면 'frontend/' 와 같이 지정
          parent: false # 'path'에 지정된 폴더 자체가 아닌, 그 안의 내용만 업로드

      - name: Discord Notification (Success)
        if: success() # 이전 단계가 모두 성공했을 때만 실행
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }} # 전체 웹훅 URL 사용
          username: 'GCP Deploy Bot'
          avatarUrl: 'https://avatars.githubusercontent.com/u/9919?s=200&v=4'
          severity: info
          title: '✅ React App 배포 성공!'
          description: 'GCS 버킷 `${{ env.GCS_BUCKET_NAME }}`에 React 앱 배포가 성공적으로 완료되었습니다.'
          details: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'

      - name: Discord Notification (Failure)
        if: failure() # 이전 단계 중 하나라도 실패했을 때 실행
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }} # 전체 웹훅 URL 사용
          username: 'GCP Deploy Bot'
          avatarUrl: 'https://avatars.githubusercontent.com/u/9919?s=200&v=4'
          severity: error
          title: '❌ React App 배포 실패!'
          description: 'GCS 버킷 `${{ env.GCS_BUCKET_NAME }}`에 React 앱 배포가 실패했습니다. 로그를 확인해주세요.'
          details: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
